name: Daily Stock Report to LINE

on:
  schedule:
    - cron: '10 8 * * 1-5'  # 每週一至五 台灣時間下午 16:10 執行
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests yfinance

      - name: Run script
        run: python stock_notify.py
        env:
          LINE_NOTIFY_TOKEN: ${{ secrets.LINE_NOTIFY_TOKEN }}
